name: sql-course
channels:
  - conda-forge
dependencies:
  - matplotlib
  - seaborn
  - numpy
  - keyring
  - pandas
  - python-duckdb
  - python-dotenv
  - ploomber
  - pip
  - ipywidgets
  - pip:
    - jupyter-book
    - pkgmt>=0.1.7
    - duckdb==0.8.1
    - duckdb-engine==0.9.1
    - jupysql-plugin
    - jupysql==0.7.0
    - urllib3==1.26.6
    - voila==0.4.1
    - itables==1.5.3
