# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application - movie recommender system 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Create env
      run: |
          cd mini-projects/movie-rec-system/
          touch .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry pytest
        cd mini-projects/movie-rec-system/
        poetry lock
        poetry install --no-root
    - name: Test with pytest
      run: |
        cd mini-projects/movie-rec-system/
        poetry run ploomber build
        poetry run pytest
